# Generated by Django 6.1.1 on 2026-09-24 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(0, 'Норма часов не может быть отрицательной.')], verbose_name='Часов в день')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Норма часов',
                'verbose_name_plural': 'Нормы часов',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('plan_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'План не может быть отрицательным.')], verbose_name='План, ч')),
                ('due_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Срок должен быть не меньше 1 дня.')], verbose_name='Срок, дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Типовая задача',
                'verbose_name_plural': 'Типовые задачи',
                'ordering': ['name'],
            },
        ),
    ]
