# Generated by Django 6.1.1 on 2026-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_working', models.BooleanField(default=False, help_text='True — перенесённый рабочий день (выходной стал рабочим).', verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Праздничный / перенесённый день',
                'verbose_name_plural': 'Праздничные и перенесённые дни',
                'ordering': ['date'],
            },
        ),
    ]
