# Generated by Django 6.1.1 on 2026-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Производственный день', 'verbose_name_plural': 'Производственный календарь'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='kind',
            field=models.CharField(choices=[('holiday', 'Праздник (нерабочий)'), ('transfer', 'Перенос выходного'), ('workday', 'Рабочий выходной'), ('short', 'Сокращённый день')], default='holiday', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
