# Generated by Django 6.1.1 on 2026-10-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_holiday_options_holiday_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='kind',
        ),
    ]
