# Generated by Django 6.1.1 on 2026-09-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('toggle', 'Вкл/выкл'), ('login_as', 'Вход от имени')], max_length=15, verbose_name='Действие')),
                ('target_model', models.CharField(max_length=60, verbose_name='Модель')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('target_repr', models.CharField(blank=True, max_length=300, verbose_name='Объект')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='admin_panel_target__3873b3_idx')],
            },
        ),
    ]
