# Generated by Django 6.1.1 on 2026-09-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.CharField(blank=True, max_length=254, verbose_name='Email при попытке')),
                ('success', models.BooleanField(default=False, verbose_name='Успех')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие входа',
                'verbose_name_plural': 'Журнал входов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='admin_panel_user_id_e76c65_idx'), models.Index(fields=['success', 'created_at'], name='admin_panel_success_cbb7b8_idx')],
            },
        ),
    ]
