# Generated by Django 6.1.1 on 2026-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_loginevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('failed_logins', 'Серия отказов входа'), ('single_admin', 'Один администратор'), ('no_norm', 'Нет нормы часов')], max_length=30, verbose_name='Тип')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Ключ дедупликации')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warn', 'Внимание'), ('danger', 'Тревога')], default='warn', max_length=10, verbose_name='Серьёзность')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Срабатываний')),
                ('seen', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последнее срабатывание')),
            ],
            options={
                'verbose_name': 'Уведомление администратора',
                'verbose_name_plural': 'Уведомления администратора',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
