# Generated by Django 6.1.1 on 2026-09-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_logins_threshold', models.PositiveIntegerField(default=5, help_text='Сколько неудачных попыток за окно считать тревогой.', verbose_name='Порог отказов входа')),
                ('failed_logins_window_min', models.PositiveIntegerField(default=15, help_text='За сколько минут считать отказы.', verbose_name='Окно, мин')),
                ('single_admin_alert', models.BooleanField(default=True, verbose_name='Оповещать про одного админа')),
                ('no_norm_alert', models.BooleanField(default=True, verbose_name='Оповещать про отсутствие нормы')),
                ('notify_email', models.EmailField(blank=True, help_text='Если задан — при новых алертах будет отправляться письмо.', max_length=254, verbose_name='Email для уведомлений')),
                ('notify_on_danger_only', models.BooleanField(default=False, help_text='Если включено — письма только для severity=danger.', verbose_name='Только тревожные алерты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('all', 'Все пользователи'), ('department', 'Подразделение'), ('role', 'Роль'), ('admins', 'Только админы')], max_length=20, verbose_name='Кому')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='Сегмент')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('recipients_total', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('recipients_sent', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('recipients_failed', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
