# Generated by Django 6.1.1 on 2026-09-24 17:55

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('can_manage', models.BooleanField(default=False, verbose_name='Управление задачами и приёмкой')),
                ('can_admin', models.BooleanField(default=False, verbose_name='Права администратора')),
                ('can_plant', models.BooleanField(default=False, verbose_name='Свод по заводу')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Корпоративная почта')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('department_hint', models.CharField(blank=True, max_length=150, verbose_name='Подразделение при регистрации')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('graphite', 'Графит'), ('ocean', 'Океан'), ('forest', 'Тайга'), ('sand', 'Песок'), ('contrast', 'Контрастная')], default='dark', max_length=10, verbose_name='Тема')),
                ('font_size', models.CharField(choices=[('s', 'Компактный'), ('m', 'Обычный'), ('l', 'Крупный')], default='m', max_length=1, verbose_name='Размер шрифта')),
                ('sound_on', models.BooleanField(default=True, verbose_name='Звук уведомлений')),
                ('bg_style', models.CharField(choices=[('grad', 'Градиент темы'), ('solid', 'Однотонный'), ('mesh', 'Мягкие пятна'), ('grid', 'Сетка'), ('custom', 'Свой цвет'), ('image', 'Своя картинка')], default='grad', max_length=10, verbose_name='Фон')),
                ('bg_color', models.CharField(blank=True, default='', max_length=7, verbose_name='Свой цвет фона')),
                ('bg_image', models.FileField(blank=True, null=True, upload_to='bg/', verbose_name='Картинка фона')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('idle_since', models.DateTimeField(blank=True, null=True, verbose_name='Простой с')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('last_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Последний исполнитель')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='Подразделение')),
                ('last_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department', verbose_name='Последнее подразделение')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_since', models.DateTimeField(verbose_name='Простой начался')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Минут простоя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформировано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отчёт по активности',
                'verbose_name_plural': 'Отчёты по активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Жалоба / ошибка'), ('idea', 'Предложение по развитию'), ('question', 'Вопрос')], default='bug', max_length=10, verbose_name='Тип')),
                ('text', models.TextField(max_length=2000, verbose_name='Сообщение')),
                ('page', models.CharField(blank=True, max_length=200, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('done', models.BooleanField(default=False, verbose_name='Обработано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Обращение в техподдержку',
                'verbose_name_plural': 'Обращения в техподдержку',
                'ordering': ['-created_at'],
            },
        ),
    ]
