# Generated by Django 6.1.1 on 2026-09-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_export',
            field=models.BooleanField(default=False, help_text='Выгрузка отчётов в CSV/XLSX.', verbose_name='Экспорт отчётов'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_analytics',
            field=models.BooleanField(default=False, help_text='Сводные отчёты по всем подразделениям.', verbose_name='Видеть аналитику по отделам'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_kpi',
            field=models.BooleanField(default=False, help_text='Доступ к отчёту KPI в кабинете (с учётом области видимости).', verbose_name='Видеть KPI'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_online',
            field=models.BooleanField(default=False, help_text='Доступ к странице «Кто онлайн» и активным сессиям.', verbose_name='Видеть кто онлайн'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_orders',
            field=models.BooleanField(default=False, help_text='Просмотр списка заказов и веток. Редактирование — только у админа.', verbose_name='Видеть заказы'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_problems',
            field=models.BooleanField(default=False, help_text='Доступ к диагностике аномалий в задачах.', verbose_name='Видеть проблемные задачи'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_sessions',
            field=models.BooleanField(default=False, help_text='Доступ к журналу сессий работы и цеха.', verbose_name='Видеть сессии сотрудников'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_task_logs',
            field=models.BooleanField(default=False, help_text='Доступ к журналу событий по задачам.', verbose_name='Видеть логи задач'),
        ),
    ]
