# Generated by Django 6.1.1 on 2026-09-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_can_export_role_can_view_analytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('graphite', 'Графит'), ('ocean', 'Океан'), ('forest', 'Тайга'), ('sand', 'Песок'), ('contrast', 'Контрастная')], default='light', max_length=10, verbose_name='Тема'),
        ),
    ]
