# Generated by Django 6.1.1 on 2026-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_digest_daily',
            field=models.BooleanField(default=False, help_text='Присылать одно письмо утром со списком задач на день.', verbose_name='Утренний дайджест'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Присылать письма о новых задачах, возвратах на доработку и приёмке.', verbose_name='Email-уведомления'),
        ),
    ]
