# Generated by Django 6.1.1 on 2026-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_digest_daily_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_seen',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь {tour_id: ISO-время прохождения}.', verbose_name='Пройденные туры'),
        ),
    ]
