# Generated by Django 6.1.1 on 2026-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_tour_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_done',
            field=models.BooleanField(default=False, help_text='True после финального экрана «Ты готов».', verbose_name='Онбординг завершён'),
        ),
    ]
