# Generated by Django 6.1.1 on 2026-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_onboarding_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='dismissed_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Причина увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Работает'), ('vacation', 'Отпуск / больничный'), ('maternity', 'Декрет'), ('dismissed', 'Уволен'), ('archived', 'Архив')], db_index=True, default='active', max_length=15, verbose_name='Статус занятости'),
        ),
    ]
