# Generated by Django 6.1.1

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_dismissed_at_user_dismissed_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hours_per_day',
            field=models.FloatField(
                blank=True,
                help_text=(
                    'Если задано — переопределяет глобальную норму для всех '
                    'сотрудников этого подразделения. Например, 12 для цеха '
                    'со сменным графиком. Оставьте пустым, чтобы использовать '
                    'глобальную норму.'
                ),
                null=True,
                validators=[django.core.validators.MinValueValidator(
                    0.1, 'Норма часов должна быть больше нуля.',
                )],
                verbose_name='Часов в день',
            ),
        ),
    ]
