# Generated by Django 6.1.1 on 2026-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_department_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_credit_days',
            field=models.IntegerField(default=0, help_text='Сколько рабочих дней исполнитель занят срочными задачами сверх плановых. Используется при пересчёте сдвига остальных его задач.', verbose_name='Срочная нагрузка, раб. дн.'),
        ),
    ]
