# Generated by Django 6.1.1 on 2026-10-03 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_shift_credit_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('pattern', models.JSONField(help_text='Список 0/1. 1 — рабочий день, 0 — выходной. Например, [1,1,1,1,1,0,0] — пятидневка, [1,1,0,0] — 2/2, [1,1,1,1,1,1,1,0,0,0,0,0,0,0] — 7/7.', verbose_name='Паттерн')),
                ('hours_per_shift', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(0.1, 'Часов в смене должно быть больше нуля.')], verbose_name='Часов в смене')),
                ('anchor_date', models.DateField(help_text='День, в который цикл начинался «с первого элемента паттерна». От него отсчитывается позиция в цикле. Для стандартной пятидневки — любой понедельник.', verbose_name='Начало цикла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='default_schedule',
            field=models.ForeignKey(blank=True, help_text='Применяется ко всем сотрудникам отдела без личного графика. Если не задан — используется встроенная логика: пн–пт, 8 ч, праздники РФ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.workschedule', verbose_name='График по умолчанию'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Если задан — перебивает график отдела. Оставьте пустым, чтобы использовать график подразделения или встроенный 5/2×8.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.workschedule', verbose_name='Личный график работы'),
        ),
    ]
