# Generated by Django 6.1.1 on 2026-09-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, verbose_name='Номер заказа')),
                ('product', models.CharField(max_length=200, verbose_name='Изделие')),
                ('ship_due', models.DateField(blank=True, null=True, verbose_name='Срок отгрузки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['ship_due'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Задача')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена')], default='new', max_length=15, verbose_name='Статус')),
                ('scale', models.CharField(choices=[('xs', 'Минуты'), ('s', 'Часы'), ('m', 'Дни'), ('l', 'Недели'), ('xl', 'Месяцы / проект')], default='s', max_length=2, verbose_name='Масштаб')),
                ('kind', models.CharField(choices=[('work', 'Работа'), ('design', 'Конструкция'), ('tech', 'Технология'), ('supply', 'Закупка')], default='work', max_length=10, verbose_name='Вид работы')),
                ('plan_hours', models.FloatField(default=0, verbose_name='План, ч')),
                ('start_due', models.DateField(blank=True, null=True, verbose_name='Срок начала')),
                ('due', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('body', models.TextField(blank=True, verbose_name='Тело задачи (что считается результатом)')),
                ('accumulated_hours', models.FloatField(default=0.0, verbose_name='Накопленное время, ч')),
                ('warehouse', models.BooleanField(default=False, verbose_name='Прибыло на склад')),
                ('notified_overdue', models.BooleanField(default=False, verbose_name='О просрочке оповещено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('session_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Текущий сеанс начат')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.order', verbose_name='Заказ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task', verbose_name='Родительская задача')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Постановщик')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.tasktype', verbose_name='Типовая задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='ShopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Выход в цех')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Возврат из цеха')),
                ('duration_hours', models.FloatField(default=0.0, verbose_name='Длительность, ч')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_sessions', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Сеанс в цехе',
                'verbose_name_plural': 'Сеансы в цехе',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rework', 'Возврат на доработку'), ('accept', 'Принято'), ('close', 'Закрыто'), ('plan', 'Изменён план'), ('due', 'Изменён срок'), ('prio', 'Изменён приоритет'), ('cancel', 'Отменена')], max_length=10, verbose_name='Событие')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_logs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Журнал задачи',
                'verbose_name_plural': 'Журналы задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запись о ходе задачи',
                'verbose_name_plural': 'Записи о ходе задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Дата снимка')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена')], max_length=15, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, verbose_name='Приоритет')),
                ('plan_hours', models.FloatField(default=0, verbose_name='План, ч')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_snapshots', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Снимок хронологии',
                'verbose_name_plural': 'Снимки хронологии',
                'ordering': ['-snapshot_date', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Старт')),
                ('finished_at', models.DateTimeField(verbose_name='Финиш')),
                ('duration_hours', models.FloatField(verbose_name='Длительность, ч')),
                ('status_at_close', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена')], max_length=15, verbose_name='Статус на закрытии')),
                ('comment', models.TextField(blank=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Сеанс работы',
                'verbose_name_plural': 'Сеансы работы',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Неделя с')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_commits', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_commits', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Обязательство на неделю',
                'verbose_name_plural': 'Обязательства на неделю',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due'], name='task_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['executor', 'status'], name='task_executor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['requester', 'status'], name='task_requester_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['finished_at'], name='task_finished_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelinesnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_date', 'task'), name='unique_timeline_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='weekcommit',
            constraint=models.UniqueConstraint(fields=('user', 'task', 'week_start'), name='unique_week_commit'),
        ),
    ]
