# Generated by Django 6.1.1 on 2026-09-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_priority_alter_timelinesnapshot_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='shift_days',
            field=models.IntegerField(blank=True, help_text='Для логов сдвига сроков: +N или −N', null=True, verbose_name='Дней сдвига'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_source_logs', to='tasks.task', verbose_name='Источник сдвига'),
        ),
    ]
