# Generated by Django 6.1.1 on 2026-09-26 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasklog_shift_days_tasklog_source_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by_stage',
            field=models.BooleanField(default=False, verbose_name='Заблокирована предыдущим этапом'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер этапа. Пусто = вне цепочки.', null=True, verbose_name='Этап в ветке'),
        ),
        migrations.CreateModel(
            name='TaskBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ветки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tasks.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Ветка заказа',
                'verbose_name_plural': 'Ветки заказа',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskbranch', verbose_name='Ветка заказа'),
        ),
        migrations.AddConstraint(
            model_name='taskbranch',
            constraint=models.UniqueConstraint(fields=('order', 'name'), name='unique_branch_per_order'),
        ),
    ]
