# Generated by Django 6.1.1 on 2026-09-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_blocked_by_stage_task_stage_order_taskbranch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending_shift_days',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется, когда предыдущий этап просрочен. Руководитель решает: сдвинуть или активировать как есть.', null=True, verbose_name='Запрошенный сдвиг, дней'),
        ),
        migrations.AddField(
            model_name='task',
            name='pending_shift_from_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_shift_children', to='tasks.task', verbose_name='Просроченный этап-источник'),
        ),
    ]
