# Generated by Django 6.1.1 on 2026-09-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_pending_shift_days_task_pending_shift_from_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала контракта'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_end',
            field=models.DateField(blank=True, null=True, verbose_name='Срок окончания проектирования'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_start',
            field=models.DateField(blank=True, null=True, verbose_name='Срок начала проектирования'),
        ),
    ]
