# Generated by Django 6.1.1 on 2026-09-30 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_dismissed_at_user_dismissed_reason_and_more'),
        ('tasks', '0006_order_contract_start_order_design_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('work', 'Работа'), ('design', 'Конструкция'), ('tech', 'Технология'), ('supply', 'Закупка')], max_length=20, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена'), ('pending_approval', 'Ожидает согласования')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='kind',
            field=models.CharField(choices=[('rework', 'Возврат на доработку'), ('accept', 'Принято'), ('close', 'Закрыто'), ('plan', 'Изменён план'), ('due', 'Изменён срок'), ('prio', 'Изменён приоритет'), ('cancel', 'Отменена'), ('shift_requested', 'Запрошен сдвиг сроков'), ('shift_approved', 'Сдвиг одобрен'), ('shift_squeezed', 'Ужали сроки'), ('shift_rejected', 'Сдвиг отклонён')], max_length=20, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='timelinesnapshot',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена'), ('pending_approval', 'Ожидает согласования')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='timesession',
            name='status_at_close',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Готово'), ('cancelled', 'Отменена'), ('pending_approval', 'Ожидает согласования')], max_length=20, verbose_name='Статус на закрытии'),
        ),
        migrations.CreateModel(
            name='PlanShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Почему задача требует сдвига других планов. Обязательно.', verbose_name='Обоснование срочности')),
                ('shift_days', models.PositiveIntegerField(default=0, verbose_name='Запрошенный сдвиг, дней')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Одобрен сдвиг'), ('squeezed', 'Ужали сроки'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=15, verbose_name='Статус')),
                ('current_level', models.CharField(choices=[('deputy', 'Заместители отдела'), ('manager', 'Руководитель отдела'), ('plant', 'Начальник завода')], default='deputy', max_length=15, verbose_name='Текущий уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('escalate_at', models.DateTimeField(db_index=True, help_text='Если никто не отреагирует до этого времени — следующий уровень.', verbose_name='Эскалировать в')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено')),
                ('decision_note', models.TextField(blank=True, verbose_name='Комментарий к решению')),
                ('affected_tasks', models.ManyToManyField(blank=True, related_name='planned_shifts', to='tasks.task', verbose_name='Задачи, которые сдвинутся')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='accounts.department', verbose_name='Отдел исполнителя')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_shift_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор (постановщик)')),
                ('recipients', models.ManyToManyField(blank=True, related_name='shift_requests_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Текущие согласующие')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_shift_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто решил')),
                ('source_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='tasks.task', verbose_name='Задача-виновник')),
            ],
            options={
                'verbose_name': 'Заявка на сдвиг плана',
                'verbose_name_plural': 'Заявки на сдвиг плана',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanShiftStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('deputy', 'Заместители отдела'), ('manager', 'Руководитель отдела'), ('plant', 'Начальник завода')], max_length=15, verbose_name='Уровень')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('decision', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрил'), ('rejected', 'Отклонил'), ('squeezed', 'Ужал сроки'), ('timeout', 'Проигнорировал')], default='pending', max_length=15, verbose_name='Решение')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено в')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.planshiftrequest', verbose_name='Заявка')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_steps', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Шаг согласования',
                'verbose_name_plural': 'Шаги согласования',
                'ordering': ['request', 'sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='planshiftrequest',
            index=models.Index(fields=['status', 'escalate_at'], name='tasks_plans_status_829901_idx'),
        ),
        migrations.AddIndex(
            model_name='planshiftrequest',
            index=models.Index(fields=['department', 'status'], name='tasks_plans_departm_1d2ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='planshiftstep',
            index=models.Index(fields=['request', 'level'], name='tasks_plans_request_9ab8fd_idx'),
        ),
    ]
