# Generated by Django 6.1.1 on 2026-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_kind_alter_task_status_alter_tasklog_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinesnapshot',
            name='accumulated_hours',
            field=models.FloatField(default=0, verbose_name='Накоплено на конец дня, ч'),
        ),
        migrations.AddField(
            model_name='timelinesnapshot',
            name='due_before',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн до сдвига'),
        ),
        migrations.AddField(
            model_name='timelinesnapshot',
            name='hours_today',
            field=models.FloatField(default=0, verbose_name='Списано за день, ч'),
        ),
        migrations.AddField(
            model_name='timelinesnapshot',
            name='status_changed',
            field=models.BooleanField(default=False, verbose_name='Статус изменился с прошлого снимка'),
        ),
    ]
