# Generated by Django 6.1.1 on 2026-09-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holiday'),
        ('tasks', '0008_timelinesnapshot_accumulated_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, help_text='Подставляется первым при генерации плана нового заказа.', verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон заказа',
                'verbose_name_plural': 'Шаблоны заказов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Внутри одной ветки этапы идут по возрастанию.', verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('branch_name', models.CharField(blank=True, help_text='Пусто — задача вне ветки.', max_length=150, verbose_name='Ветка')),
                ('executor_role_code', models.CharField(blank=True, help_text='Если задано — ищем активного сотрудника этой роли в отделе заказа.', max_length=50, verbose_name='Роль исполнителя (код)')),
                ('offset_anchor', models.CharField(choices=[('contract_start', 'Начало контракта'), ('design_start', 'Старт проектирования'), ('design_end', 'Конец проектирования'), ('ship_due', 'Отгрузка')], default='contract_start', max_length=20, verbose_name='Точка отсчёта')),
                ('offset_days', models.IntegerField(default=0, help_text='Плюс — позже точки, минус — раньше. Считается по рабочим дням.', verbose_name='Смещение, раб. дней')),
                ('duration_days', models.PositiveIntegerField(default=5, verbose_name='Длительность, раб. дней')),
                ('plan_hours', models.FloatField(default=0.0, help_text='0 — если задана типовая, берём часы из неё.', verbose_name='План, ч')),
                ('use_task_type_hours', models.BooleanField(default=True, verbose_name='Брать часы из типовой')),
                ('kind', models.CharField(blank=True, choices=[('work', 'Работа'), ('design', 'Конструкция'), ('tech', 'Технология'), ('supply', 'Закупка')], help_text='Пусто — унаследуется от типовой или work.', max_length=20, verbose_name='Вид работы')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('task_type', models.ForeignKey(blank=True, help_text='Из неё берётся план часов и вид работы, если не задано явно.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasktype', verbose_name='Типовая задача')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.ordertemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Этап шаблона',
                'verbose_name_plural': 'Этапы шаблона',
                'ordering': ['template', 'order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'order'), name='unique_template_stage_order')],
            },
        ),
    ]
