# Generated by Django 6.1.1 on 2026-09-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_dismissed_at_user_dismissed_reason_and_more'),
        ('tasks', '0009_ordertemplate_ordertemplatestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeptMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('tasks_open', models.PositiveIntegerField(default=0, verbose_name='Открытых')),
                ('tasks_done_today', models.PositiveIntegerField(default=0, verbose_name='Закрыто за день')),
                ('tasks_overdue', models.PositiveIntegerField(default=0, verbose_name='Просрочено')),
                ('plan_hours_open', models.FloatField(default=0, verbose_name='План открытых, ч')),
                ('fact_hours_today', models.FloatField(default=0, verbose_name='Факт за день, ч')),
                ('shop_hours_today', models.FloatField(default=0, verbose_name='Цех за день, ч')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Сеансов')),
                ('employees_active', models.PositiveIntegerField(default=0, verbose_name='Сотрудников работало')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='accounts.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Дневной срез отдела',
                'verbose_name_plural': 'Дневные срезы отделов',
                'ordering': ['-date', 'department__name'],
                'indexes': [models.Index(fields=['department', '-date'], name='tasks_daily_departm_ce017c_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'department'), name='unique_daily_dept_metrics')],
            },
        ),
    ]
