# Generated by Django 6.1.1 on 2026-10-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_dailydeptmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Получает уведомления о приближении контрольных точек.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за заказ'),
        ),
        migrations.CreateModel(
            name='OrderDeadlineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(choices=[('contract_start', 'Начало контракта'), ('design_start', 'Старт проектирования'), ('design_end', 'Конец проектирования'), ('ship_due', 'Отгрузка')], max_length=20, verbose_name='Контрольная точка')),
                ('days_before', models.PositiveIntegerField(help_text='7 или 3. Может быть больше, если добавишь свои пороги.', verbose_name='За сколько раб. дней')),
                ('anchor_date', models.DateField(help_text='Фиксируем — чтобы если срок переехал, уведомление отправилось заново.', verbose_name='Дата точки на момент отправки')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='tasks.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Уведомление о точке заказа',
                'verbose_name_plural': 'Уведомления о точках заказов',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['order', '-sent_at'], name='tasks_order_order_i_7bedca_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'anchor', 'days_before', 'anchor_date'), name='unique_order_deadline_notification')],
            },
        ),
    ]
