# Generated by Django 6.1.1 on 2026-10-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_order_owner_orderdeadlinenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pending_shift_from_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task', verbose_name='Просроченный этап-источник'),
        ),
    ]
