# Generated by Django 6.1.1 on 2026-10-02 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_pending_shift_from_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopsession',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('executor',), name='unique_open_shop_session_per_user'),
        ),
    ]
