# Generated by Django 6.1.1 on 2026-10-03 06:41

from django.db import migrations, models
from django.db.models import F


def copy_current_to_original(apps, schema_editor):
    """Скопировать текущие start_due/due в original_* для существующих задач.

    Это делается один раз при миграции, чтобы задачи, у которых уже были
    сроки, получили «базовые» значения. Дальше сдвиги будут пересчитываться
    от original_*, а не от текущих due.
    """
    Task = apps.get_model('tasks', 'Task')

    Task.objects.filter(
        original_start_due__isnull=True,
        start_due__isnull=False,
    ).update(original_start_due=F('start_due'))

    Task.objects.filter(
        original_due__isnull=True,
        due__isnull=False,
    ).update(original_due=F('due'))


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_shop_session_unique_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_due',
            field=models.DateField(
                blank=True,
                help_text='Дедлайн на момент постановки задачи. Не меняется при сдвигах.',
                null=True,
                verbose_name='Исходный дедлайн',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='original_start_due',
            field=models.DateField(
                blank=True,
                help_text=(
                    'Срок начала на момент постановки задачи. '
                    'Используется для пересчёта сдвига: срочные двигают сроки, '
                    'но всегда от этой базовой даты, чтобы не накапливать ошибку.'
                ),
                null=True,
                verbose_name='Исходный срок начала',
            ),
        ),
        migrations.RunPython(copy_current_to_original, migrations.RunPython.noop),
    ]
