# Generated by Django 6.1.1 on 2026-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_original_due_task_original_start_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_shift_days',
            field=models.PositiveIntegerField(default=0, help_text='Сколько рабочих дней срочная задача «съела» на момент создания. Используется при коррекции сдвига после закрытия: факт − план = досдвиг или откат.', verbose_name='Запланировано срочной, раб. дн.'),
        ),
    ]
