# Generated by Django 6.1.1 on 2026-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_planned_shift_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_due',
            field=models.DateField(blank=True, help_text='Обещание заказчику. Видно постановщику, руководителю отдела исполнителя и администратору. Исполнитель его не видит. Не сдвигается при срочных.', null=True, verbose_name='Формальный срок (для заказчика)'),
        ),
    ]
