# Generated by Django 6.1.1 on 2026-10-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_shift_credit_days'),
        ('tasks', '0016_task_external_due'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('hours', models.FloatField(help_text='Сколько часов сверхурочно в этот день.', verbose_name='Часы')),
                ('reason', models.CharField(blank=True, help_text='Например: ремонт станка, аварийный пуск, инвентаризация.', max_length=500, verbose_name='Причина')),
                ('order_file', models.FileField(blank=True, null=True, upload_to='overtime/%Y/%m/', verbose_name='Приказ / основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда внесено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс')),
                ('department', models.ForeignKey(blank=True, help_text='Фиксируется на момент записи, чтобы перевод не менял историю.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='accounts.department', verbose_name='Отдел (снапшот)')),
                ('task', models.ForeignKey(blank=True, help_text='Опционально. Оставьте пустым для работ «на общие нужды».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сверхурочная',
                'verbose_name_plural': 'Сверхурочные',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='tasks_overt_user_id_fcdff7_idx'), models.Index(fields=['department', '-date'], name='tasks_overt_departm_cd9ac8_idx')],
            },
        ),
    ]
