# Generated by Django 6.1.1 on 2026-09-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_days', models.PositiveIntegerField(default=0, verbose_name='Текущая серия, дней')),
                ('best_days', models.PositiveIntegerField(default=0, verbose_name='Рекордная серия, дней')),
                ('last_ok_date', models.DateField(blank=True, null=True, verbose_name='Последний день без просрочки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Серия без просрочек',
                'verbose_name_plural': 'Серии без просрочек',
            },
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kudos_sent', to=settings.AUTH_USER_MODEL, verbose_name='Кто поблагодарил')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kudos_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Благодарность',
                'verbose_name_plural': 'Благодарности',
                'indexes': [models.Index(fields=['to_user', 'created_at'], name='kudos_to_user_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='kudos_not_self')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamify.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выданное достижение',
                'verbose_name_plural': 'Выданные достижения',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
